2025-10-08 02:12:07 [INFO] {"event_type":"auth_failure","timestamp":"2025-10-07T22:43:53.829543","user_id":null,"ip_address":"127.0.0.1","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0","path":"/api/v1/auth/login","method":"POST","details":{"email":"admin@example.com","failed_attempts":1,"reason":"invalid_credentials"},"severity":1}
2025-10-08 02:13:20 [INFO] {"event_type":"auth_failure","timestamp":"2025-10-07T23:12:44.864725","user_id":null,"ip_address":"127.0.0.1","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0","path":"/api/v1/auth/login","method":"POST","details":{"email":"admin@example.com","failed_attempts":2,"reason":"invalid_credentials"},"severity":1}
2025-10-08 02:13:23 [INFO] {"event_type":"auth_failure","timestamp":"2025-10-07T23:12:44.864725","user_id":null,"ip_address":"127.0.0.1","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0","path":"/api/v1/auth/login","method":"POST","details":{"email":"admin@example.com","failed_attempts":3,"reason":"invalid_credentials"},"severity":1}
2025-10-08 12:16:57 [INFO] {"event_type":"auth_failure","timestamp":"2025-10-07T23:43:55.419956","user_id":null,"ip_address":"127.0.0.1","user_agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/141.0.0.0 Safari/537.36 Edg/141.0.0.0","path":"/api/v1/auth/login","method":"POST","details":{"email":"admin@example.com","failed_attempts":1,"reason":"invalid_credentials"},"severity":1}
2025-10-08 12:17:35 [INFO] {"event_type":"auth_failure","timestamp":"2025-10-07T23:43:55.419956","user_id":null,"ip_address":"127.0.0.1","user_agent":"curl/8.13.0","path":"/api/v1/auth/login","method":"POST","details":{"email":"admin@example.com","failed_attempts":2,"reason":"invalid_credentials"},"severity":1}
2025-10-10 02:31:35 [ERROR] Top-level exception caught by diagnostics middleware: Object of type MagicMock is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in call_next
    message = await recv_stream.receive()
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\temp\GplusApp-main-merge\backend\app\core\security_monitoring.py", line 353, in dispatch
    return await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\middlewares\security.py", line 39, in dispatch
    return await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\core\middleware\cache_control.py", line 119, in dispatch
    response = await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\core\middleware\cache_performance.py", line 45, in dispatch
    response = await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 75, in app
    response = await f(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 302, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 213, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\temp\GplusApp-main-merge\backend\app\core\redis_fastapi.py", line 289, in wrapper
    response = JSONResponse(content=convert_sqlalchemy_to_dict(response))
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 190, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 47, in __init__
    self.body = self.render(content)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 193, in render
    return json.dumps(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MagicMock is not JSON serializable
2025-10-10 02:32:52 [ERROR] Top-level exception caught by diagnostics middleware: Object of type MagicMock is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in call_next
    message = await recv_stream.receive()
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\temp\GplusApp-main-merge\backend\app\core\security_monitoring.py", line 353, in dispatch
    return await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\middlewares\security.py", line 39, in dispatch
    return await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\core\middleware\cache_control.py", line 119, in dispatch
    response = await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\core\middleware\cache_performance.py", line 45, in dispatch
    response = await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 75, in app
    response = await f(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 302, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 213, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\temp\GplusApp-main-merge\backend\app\core\redis_fastapi.py", line 289, in wrapper
    response = JSONResponse(content=convert_sqlalchemy_to_dict(response))
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 190, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 47, in __init__
    self.body = self.render(content)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 193, in render
    return json.dumps(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MagicMock is not JSON serializable
2025-10-10 02:33:45 [ERROR] Top-level exception caught by diagnostics middleware: Object of type MagicMock is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in call_next
    message = await recv_stream.receive()
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\temp\GplusApp-main-merge\backend\app\core\security_monitoring.py", line 353, in dispatch
    return await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\middlewares\security.py", line 39, in dispatch
    return await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\core\middleware\cache_control.py", line 119, in dispatch
    response = await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\core\middleware\cache_performance.py", line 45, in dispatch
    response = await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 75, in app
    response = await f(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 302, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 213, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\temp\GplusApp-main-merge\backend\app\core\redis_fastapi.py", line 289, in wrapper
    response = JSONResponse(content=convert_sqlalchemy_to_dict(response))
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 190, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 47, in __init__
    self.body = self.render(content)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 193, in render
    return json.dumps(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MagicMock is not JSON serializable
2025-10-10 02:35:16 [ERROR] Top-level exception caught by diagnostics middleware: Object of type MagicMock is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in call_next
    message = await recv_stream.receive()
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\temp\GplusApp-main-merge\backend\app\core\security_monitoring.py", line 353, in dispatch
    return await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\middlewares\security.py", line 39, in dispatch
    return await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\core\middleware\cache_control.py", line 119, in dispatch
    response = await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\core\middleware\cache_performance.py", line 45, in dispatch
    response = await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 75, in app
    response = await f(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 302, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 213, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\temp\GplusApp-main-merge\backend\app\core\redis_fastapi.py", line 289, in wrapper
    response = JSONResponse(content=convert_sqlalchemy_to_dict(response))
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 190, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 47, in __init__
    self.body = self.render(content)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 193, in render
    return json.dumps(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MagicMock is not JSON serializable
2025-10-10 02:37:36 [ERROR] Top-level exception caught by diagnostics middleware: Object of type MagicMock is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in call_next
    message = await recv_stream.receive()
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\temp\GplusApp-main-merge\backend\app\core\security_monitoring.py", line 353, in dispatch
    return await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\middlewares\security.py", line 39, in dispatch
    return await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\core\middleware\cache_control.py", line 119, in dispatch
    response = await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\core\middleware\cache_performance.py", line 45, in dispatch
    response = await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 75, in app
    response = await f(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 302, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 213, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\temp\GplusApp-main-merge\backend\app\core\redis_fastapi.py", line 289, in wrapper
    response = JSONResponse(content=convert_sqlalchemy_to_dict(response))
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 190, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 47, in __init__
    self.body = self.render(content)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 193, in render
    return json.dumps(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MagicMock is not JSON serializable
2025-10-10 02:40:47 [ERROR] Top-level exception caught by diagnostics middleware: Object of type MagicMock is not JSON serializable
Traceback (most recent call last):
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 151, in call_next
    message = await recv_stream.receive()
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\anyio\streams\memory.py", line 126, in receive
    raise EndOfStream from None
anyio.EndOfStream

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\temp\GplusApp-main-merge\backend\app\core\security_monitoring.py", line 353, in dispatch
    return await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\middlewares\security.py", line 39, in dispatch
    return await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\cors.py", line 85, in __call__
    await self.app(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\core\middleware\cache_control.py", line 119, in dispatch
    response = await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 182, in __call__
    with recv_stream, send_stream, collapse_excgroups():
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_utils.py", line 85, in collapse_excgroups
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 184, in __call__
    response = await self.dispatch_func(request, call_next)
  File "C:\temp\GplusApp-main-merge\backend\app\core\middleware\cache_performance.py", line 45, in dispatch
    response = await call_next(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 159, in call_next
    raise app_exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\base.py", line 144, in coro
    await self.app(scope, receive_or_disconnect, send_no_error)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\middleware\exceptions.py", line 63, in __call__
    await wrap_app_handling_exceptions(self.app, conn)(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 716, in __call__
    await self.middleware_stack(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 736, in app
    await route.handle(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 290, in handle
    await self.app(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 78, in app
    await wrap_app_handling_exceptions(app, request)(scope, receive, send)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 53, in wrapped_app
    raise exc
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\_exception_handler.py", line 42, in wrapped_app
    await app(scope, receive, sender)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\routing.py", line 75, in app
    response = await f(request)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 302, in app
    raw_response = await run_endpoint_function(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\fastapi\routing.py", line 213, in run_endpoint_function
    return await dependant.call(**values)
  File "C:\temp\GplusApp-main-merge\backend\app\core\redis_fastapi.py", line 289, in wrapper
    response = JSONResponse(content=convert_sqlalchemy_to_dict(response))
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 190, in __init__
    super().__init__(content, status_code, headers, media_type, background)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 47, in __init__
    self.body = self.render(content)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\site-packages\starlette\responses.py", line 193, in render
    return json.dumps(
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "C:\Users\Moamen Ahmed\AppData\Local\Programs\Python\Python310\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type MagicMock is not JSON serializable
